import type { ScanReport, Severity } from "../types.js";

const EMOJI: Record<Severity, string> = {
  critical: "🟥",
  high: "🟧",
  medium: "🟨",
  low: "🟦",
  info: "⬜",
};

const GRADE_EMOJI: Record<string, string> = { A: "🟢", B: "🟢", C: "🟡", D: "🟠", F: "🔴" };

/** Markdown summary suitable for a PR comment or job summary. */
export function renderMarkdown(report: ScanReport): string {
  const out: string[] = [];
  out.push(`## 🛡️ skillguardian report`);
  out.push("");
  out.push(
    `**Overall grade: ${GRADE_EMOJI[report.grade] ?? ""} ${report.grade}** (score ${report.score}/100)`,
  );
  out.push("");
  const t = report.totals;
  out.push(
    `${EMOJI.critical} ${t.critical} critical · ${EMOJI.high} ${t.high} high · ${EMOJI.medium} ${t.medium} medium · ${EMOJI.low} ${t.low} low`,
  );
  out.push("");

  const withFindings = report.components.filter((c) => c.findings.length > 0);
  if (withFindings.length === 0 && report.composedRisks.length === 0) {
    out.push("✅ No issues found.");
    return out.join("\n");
  }

  if (withFindings.length > 0) {
    out.push("| Grade | Component | Rule | Severity | Location | Issue |");
    out.push("| :---: | --- | --- | --- | --- | --- |");
    for (const comp of withFindings) {
      for (const f of comp.findings) {
        const loc = f.line ? `\`${f.file}:${f.line}\`` : `\`${f.file}\``;
        const msg = f.message.replace(/\|/g, "\\|");
        out.push(
          `| ${GRADE_EMOJI[comp.grade] ?? ""} ${comp.grade} | ${comp.component.name} | \`${f.ruleId}\` | ${EMOJI[f.severity]} ${f.severity} | ${loc} | ${msg} |`,
        );
      }
    }
    out.push("");
  }

  if (report.composedRisks.length > 0) {
    out.push(`### ⚠️ Cross-skill risks`);
    out.push("");
    out.push("_Capabilities that combine across separate components — each skill may look fine alone._");
    out.push("");
    for (const r of report.composedRisks) {
      const legs = r.legs.map((l) => `${l.capability} in **${l.component}** (\`${l.ruleId}\`)`).join(" + ");
      out.push(`- **${r.id} ${r.title}** — ${legs}. ${r.message}`);
    }
    out.push("");
  }

  out.push(`<sub>Generated by [skillguardian](https://github.com/hussainu6/skillguardian)</sub>`);
  return out.join("\n");
}
